DROP TABLE IF EXISTS users, categories, compilations, events, compilation_event, requests, comments;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN,
    CONSTRAINT PK_COMPILATION PRIMARY KEY (id),
    CONSTRAINT UQ_COMPILATION_TITLE UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT,
    description        VARCHAR(7000)                           NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    lat                REAL,
    lon                REAL,
    initiator_id       BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    paid               BOOLEAN,
    participant_limit  INT                                     NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(20)                             NOT NULL,
    CONSTRAINT PK_EVENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_FOR_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_EVENT_FOR_USER FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    compilation_id BIGINT REFERENCES compilations (id),
    event_id       BIGINT REFERENCES events (id),
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT FK_EVENT_FOR_COMPIL FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_COMPIL_FOR_EVENT FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    CONSTRAINT PK_REQUESTS PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_FOR_REQUEST FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_FOR_REQUEST FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text           VARCHAR(2000)                           NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE,
    event_id       BIGINT                                  NOT NULL,
    commentator_id BIGINT                                  NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    CONSTRAINT PK_COMMENTS PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_FOR_COMMENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_FOR_COMMENT FOREIGN KEY (commentator_id) REFERENCES users (id)
);