--liquibase formatted sql

--changeset alexmaxpower:1
DROP TABLE IF EXISTS comments;

--changeset alexmaxpower:2
CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text           VARCHAR(2000)                           NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE,
    event_id       BIGINT                                  NOT NULL,
    commentator_id BIGINT                                  NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    CONSTRAINT PK_COMMENTS PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_FOR_COMMENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_FOR_COMMENT FOREIGN KEY (commentator_id) REFERENCES users (id)
);